name: accionables_linux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Paso 1 - Checkout repo
        uses: actions/checkout@v4

      - name: Paso 2 - Login docker Github
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Paso 2.1 - Configurar imagen docker
        run: docker build -t python-hello .

      - name: Paso 2.2 - Ejecutar imagen docker
        run: docker run --rm python-hello

      - name: Paso 3 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: false

      - name: Paso 4 - Crear entorno virtual
        run: python -m venv venv

      - name: Paso 5 - Activar entorno virtual
        run: source ./venv/bin/activate

      - name: Paso 6 - Actualizar pip
        run: pip install --upgrade pip

      - name: Paso 7 - Instalar dependencias
        run: pip install -e .

      - name: Paso 8 - Ejecutar Main
        run: python src/edu_pad/static/main.py

      - name: Paso 9 - Hacer pull con rebase antes del commit
        run: |
          git config --global user.name 'Juan Urrego [GitHub Actions]'
          git config --global user.email 'juan.urrego@est.iudigital.edu.co'
          git pull --rebase origin main

      - name: Paso 10 - Guardar el commit con el último cambio desde pipeline
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Genera archivo csv de la web
          commit_user_name: Juan Urrego [GitHub Actions]
          commit_user_email: juan.urrego@est.iudigital.edu.co
          commit_author: Juan Urrego <juan.urrego@est.iudigital.edu.co>
